apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-html-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-html-app
  template:
    metadata:
      labels:
        app: my-html-app
    spec:
      containers:
      - name: my-html-container
        image: quake3144/my-html-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-html-service
spec:
  type: NodePort
  selector:
    app: my-html-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008

